# Generated by Django 4.1.5 on 2023-02-05 23:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='Avatarr',
        ),
    ]
