# Generated by Django 4.1.5 on 2023-02-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_principal', '0002_autor_categoria_contacto_post_redessociales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen_referencial',
            field=models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Imagen Referencial'),
        ),
        migrations.AddField(
            model_name='autor',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='autor',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web'),
        ),
    ]
