# Generated by Django 4.1.5 on 2023-02-05 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_principal', '0004_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
